import type{D1Database}from"./db.ts";import{CATALOG_ACTION_HELP,CATALOG_GROUP_LABELS,CATALOG_GROUP_QUESTION,MUSCLE_GROUPS,parseCatalogAction,parseCatalogGroup,type CatalogGroup}from"./exercise-catalog.ts";
import{startExerciseAddConversation}from"./exercise-add-db.ts";
interface Conversation{id:number;step:1|2;selected_group:CatalogGroup|null}
interface ExerciseRow{id:number;name:string;availability:"active"|"paused"|"rare"|"unknown";priority:number;reintroduction_status:string|null}
async function pending(db:D1Database,userId:number){return db.prepare("SELECT id,step,selected_group FROM exercise_catalog_conversations WHERE user_id=? AND status='pending' AND expires_at>CURRENT_TIMESTAMP ORDER BY updated_at DESC LIMIT 1").bind(userId).first<Conversation>()}
async function rowsForGroup(db:D1Database,userId:number,group:CatalogGroup){const groups=MUSCLE_GROUPS[group],placeholders=groups.map(()=>"?").join(",");const result=await db.prepare(`SELECT exercise.id,exercise.name,settings.availability,settings.priority,reintroduction.status AS reintroduction_status FROM user_exercise_settings settings JOIN exercises exercise ON exercise.id=settings.exercise_id LEFT JOIN exercise_reintroduction_plans reintroduction ON reintroduction.user_id=settings.user_id AND reintroduction.exercise_id=exercise.id WHERE settings.user_id=? AND exercise.muscle_group IN (${placeholders}) ORDER BY settings.priority DESC,exercise.name`).bind(userId,...groups).all<ExerciseRow>();return result.results??[]}
const availabilityLabels={active:"активно",paused:"пауза",rare:"редко",unknown:"неизвестно"};
function format(group:CatalogGroup,rows:ExerciseRow[]):string{return[`Упражнения — ${CATALOG_GROUP_LABELS[group]}:`,...rows.map((row)=>`${row.id}. ${row.name} — ${availabilityLabels[row.availability]}, приоритет ${row.priority}${row.reintroduction_status?`, возврат: ${row.reintroduction_status}`:""}`),"",CATALOG_ACTION_HELP].join("\n")}
export async function startExerciseCatalogConversation(db:D1Database,userId:number):Promise<string>{const current=await pending(db,userId);if(current){if(current.step===2&&current.selected_group)return format(current.selected_group,await rowsForGroup(db,userId,current.selected_group));return CATALOG_GROUP_QUESTION}await db.prepare("UPDATE exercise_catalog_conversations SET status='expired' WHERE user_id=? AND status='pending'").bind(userId).run();await db.prepare("INSERT INTO exercise_catalog_conversations(user_id,step,status,expires_at)VALUES(?,1,'pending',datetime('now','+2 days'))").bind(userId).run();return CATALOG_GROUP_QUESTION}
export async function cancelExerciseCatalogConversation(db:D1Database,userId:number):Promise<boolean>{const row=await pending(db,userId);if(!row)return false;await db.prepare("UPDATE exercise_catalog_conversations SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(row.id).run();return true}
export async function answerExerciseCatalogConversation(db:D1Database,userId:number,text:string):Promise<string|null>{const conversation=await pending(db,userId);if(!conversation)return null;if(conversation.step===1){const group=parseCatalogGroup(text);if(!group)return`Не понял группу. ${CATALOG_GROUP_QUESTION}`;await db.prepare("UPDATE exercise_catalog_conversations SET step=2,selected_group=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(group,conversation.id).run();return format(group,await rowsForGroup(db,userId,group))}if(!conversation.selected_group)throw new Error("Повреждён диалог каталога");if(text.trim().toLocaleLowerCase("ru-RU")==="добавить"){await db.prepare("UPDATE exercise_catalog_conversations SET status='completed',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(conversation.id).run();return startExerciseAddConversation(db,userId,conversation.selected_group)}const action=parseCatalogAction(text);if(!action)return`Не понял действие. ${CATALOG_ACTION_HELP}`;if(action.kind==="back"){await db.prepare("UPDATE exercise_catalog_conversations SET step=1,selected_group=NULL,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(conversation.id).run();return CATALOG_GROUP_QUESTION}const rows=await rowsForGroup(db,userId,conversation.selected_group);const target=rows.find((row)=>row.id===action.exerciseId);if(!target)return`Упражнение №${action.exerciseId} не относится к выбранной группе.`;if(action.kind==="availability")await db.prepare("UPDATE user_exercise_settings SET availability=?,updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND exercise_id=?").bind(action.availability,userId,target.id).run();else await db.prepare("UPDATE user_exercise_settings SET priority=?,updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND exercise_id=?").bind(action.priority,userId,target.id).run();const safety=target.reintroduction_status&&action.kind==="availability"&&action.availability==="active"?" План возврата всё равно имеет приоритет и может оставить упражнение вне генерации.":"";return`«${target.name}» обновлено.${safety}\n\n${CATALOG_ACTION_HELP}`}
