import type{D1Database}from"./db.ts";import{canChangeReintroduction,parseReintroductionAction,REINTRODUCTION_HELP,type ReintroductionStatus}from"./reintroduction.ts";
interface PlanRow{exercise_id:number;name:string;status:ReintroductionStatus;load_policy:string;last_tested_on:string|null}
async function pending(db:D1Database,userId:number){return db.prepare("SELECT id FROM reintroduction_conversations WHERE user_id=? AND status='pending' AND expires_at>CURRENT_TIMESTAMP ORDER BY updated_at DESC LIMIT 1").bind(userId).first<{id:number}>()}
async function plans(db:D1Database,userId:number){const result=await db.prepare("SELECT plan.exercise_id,exercise.name,plan.status,plan.load_policy,plan.last_tested_on FROM exercise_reintroduction_plans plan JOIN exercises exercise ON exercise.id=plan.exercise_id WHERE plan.user_id=? ORDER BY exercise.name").bind(userId).all<PlanRow>();return result.results??[]}
const labels:Record<ReintroductionStatus,string>={planned:"запланировано",testing:"тестируется",established:"допущено",paused:"пауза"};
function format(rows:PlanRow[]):string{return rows.length?["Постепенный возврат упражнений:",...rows.map((row)=>`${row.exercise_id}. ${row.name} — ${labels[row.status]}${row.last_tested_on?` (тест ${row.last_tested_on})`:""}`)].join("\n"):"Планов постепенного возврата пока нет."}
export async function startReintroductionConversation(db:D1Database,userId:number):Promise<string>{const current=await pending(db,userId);if(!current){await db.prepare("UPDATE reintroduction_conversations SET status='expired' WHERE user_id=? AND status='pending'").bind(userId).run();await db.prepare("INSERT INTO reintroduction_conversations(user_id,status,expires_at)VALUES(?,'pending',datetime('now','+2 days'))").bind(userId).run()}return`${format(await plans(db,userId))}\n\n${REINTRODUCTION_HELP}\nОдновременно тестируется только одно упражнение.`}
export async function cancelReintroductionConversation(db:D1Database,userId:number):Promise<boolean>{const row=await pending(db,userId);if(!row)return false;await db.prepare("UPDATE reintroduction_conversations SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(row.id).run();return true}
export async function answerReintroductionConversation(db:D1Database,userId:number,text:string,date:string):Promise<string|null>{const conversation=await pending(db,userId);if(!conversation)return null;const action=parseReintroductionAction(text);if(!action)return`Не понял действие. ${REINTRODUCTION_HELP}`;const rows=await plans(db,userId);if(action.kind==="list")return`${format(rows)}\n\n${REINTRODUCTION_HELP}`;const target=rows.find((row)=>row.exercise_id===action.exerciseId);if(!target)return`Упражнение №${action.exerciseId} отсутствует в списке.\n\n${REINTRODUCTION_HELP}`;if(action.kind==="testing"){const another=rows.find((row)=>row.status==="testing"&&row.exercise_id!==target.exercise_id);if(another)return`Сейчас уже тестируется «${another.name}». Сначала допусти его после подтверждённого теста либо поставь на паузу.`;if(!canChangeReintroduction(target.status,"testing",Boolean(target.last_tested_on)))return`«${target.name}» нельзя перевести из состояния «${labels[target.status]}» в тестирование.`;await db.prepare("UPDATE exercise_reintroduction_plans SET status='testing',started_on=COALESCE(started_on,?),last_tested_on=NULL,updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND exercise_id=?").bind(date,userId,target.exercise_id).run()}else if(action.kind==="established"){if(!canChangeReintroduction(target.status,"established",Boolean(target.last_tested_on)))return`Сначала упражнение должно быть в тестировании и реально выполнено в подтверждённой тренировке.`;await db.prepare("UPDATE exercise_reintroduction_plans SET status='established',updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND exercise_id=?").bind(userId,target.exercise_id).run()}else{if(!canChangeReintroduction(target.status,"paused",Boolean(target.last_tested_on)))return`«${target.name}» уже на паузе.`;await db.prepare("UPDATE exercise_reintroduction_plans SET status='paused',updated_at=CURRENT_TIMESTAMP WHERE user_id=? AND exercise_id=?").bind(userId,target.exercise_id).run()}await db.prepare("UPDATE reintroduction_conversations SET status='completed',completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(conversation.id).run();const resultLabel=action.kind==="testing"?"переведено в безопасное тестирование":action.kind==="established"?"допущено в обычный каталог":"поставлено на паузу";return`«${target.name}» ${resultLabel}.`}
