import { createHash } from "node:crypto";

function parseRows(text, delimiter) {
  const rows=[];let row=[],field="",quoted=false;
  for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(char===delimiter&&!quoted){row.push(field);field=""}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(field);if(row.some((value)=>value.trim()))rows.push(row);row=[];field=""}else field+=char}
  row.push(field);if(row.some((value)=>value.trim()))rows.push(row);return rows;
}

function delimiter(text){const first=text.split(/\r?\n/,1)[0]??"";let commas=0,semicolons=0,quoted=false;for(const char of first){if(char==='"')quoted=!quoted;else if(!quoted&&char===',')commas++;else if(!quoted&&char===';')semicolons++}return semicolons>commas?';':','}
function header(value){return value.replace(/^\uFEFF/,"").trim().toLocaleLowerCase("ru-RU").replace(/[\s_.()/-]+/g,"")}
function column(headers,predicates){return headers.findIndex((value)=>predicates.some((test)=>test(value)))}
function decimal(value){const cleaned=value.trim().replace(/\s/g,"").replace(",",".").replace(/[^0-9.+-]/g,"");if(!cleaned)return null;const result=Number(cleaned);return Number.isFinite(result)&&result>=0?result:null}
function iso(year,month,day){const date=new Date(Date.UTC(year,month-1,day));if(date.getUTCFullYear()!==year||date.getUTCMonth()+1!==month||date.getUTCDate()!==day)return null;return `${year}-${String(month).padStart(2,"0")}-${String(day).padStart(2,"0")}`}
function date(value){const input=value.trim();let match=input.match(/^(\d{4})[-/.](\d{1,2})[-/.](\d{1,2})$/);if(match)return iso(Number(match[1]),Number(match[2]),Number(match[3]));match=input.match(/^(\d{1,2})[./](\d{1,2})[./](\d{4})$/);if(match){let first=Number(match[1]),second=Number(match[2]);return first>12?iso(Number(match[3]),second,first):second>12?iso(Number(match[3]),first,second):iso(Number(match[3]),second,first)}const parsed=new Date(input);return Number.isNaN(parsed.valueOf())?null:iso(parsed.getUTCFullYear(),parsed.getUTCMonth()+1,parsed.getUTCDate())}
function totalLabel(value){return /^(total|итого|всего|dailyaverage|periodsummary)$/.test(header(value))}

export function parseFatSecretCsv(text){
  const rows=parseRows(text,delimiter(text));if(rows.length<2)throw new Error("CSV не содержит строк дневника");const headers=rows[0].map(header);
  const indexes={date:column(headers,[(v)=>v==="date",(v)=>v==="дата"]),calories:column(headers,[(v)=>v.startsWith("cals"),(v)=>v.startsWith("calories"),(v)=>v.startsWith("калор"),(v)=>v==="energykcal"]),fat:column(headers,[(v)=>v==="fatg",(v)=>v==="fat",(v)=>v==="жирыг",(v)=>v==="жиры"]),carbs:column(headers,[(v)=>v.startsWith("carbs"),(v)=>v.startsWith("carbohydrate"),(v)=>v.startsWith("углев")]),protein:column(headers,[(v)=>v.startsWith("prot"),(v)=>v.startsWith("protein"),(v)=>v.startsWith("бел")]),item:column(headers,[(v)=>v==="item",(v)=>v.startsWith("food"),(v)=>v.startsWith("продукт")]),meal:column(headers,[(v)=>v==="meal",(v)=>v.startsWith("приемпищи"),(v)=>v.startsWith("приёмпищи")])};
  for(const required of ["date","calories","fat","carbs","protein"]){if(indexes[required]<0)throw new Error(`Не найдена обязательная колонка: ${required}`)}
  const days=new Map();let currentDate=null;
  for(const row of rows.slice(1)){const rawDate=row[indexes.date]??"";if(rawDate.trim()){currentDate=date(rawDate);if(!currentDate)continue}if(!currentDate)continue;const label=[indexes.item,indexes.meal].filter((index)=>index>=0).map((index)=>row[index]??"").find((value)=>totalLabel(value));if(label)continue;const values={caloriesKcal:decimal(row[indexes.calories]??""),fatG:decimal(row[indexes.fat]??""),carbohydrateG:decimal(row[indexes.carbs]??""),proteinG:decimal(row[indexes.protein]??"")};if(Object.values(values).every((value)=>value===null))continue;const existing=days.get(currentDate)??{date:currentDate,caloriesKcal:0,proteinG:0,fatG:0,carbohydrateG:0};for(const key of Object.keys(values)){existing[key]+=values[key]??0}days.set(currentDate,existing)}
  const result=[...days.values()].sort((a,b)=>a.date.localeCompare(b.date));if(!result.length)throw new Error("В CSV не найдено дневных данных КБЖУ");for(const day of result){if(day.caloriesKcal>15000||day.proteinG>1000||day.fatG>1000||day.carbohydrateG>1500)throw new Error(`Нереалистичный итог за ${day.date}`);for(const key of ["caloriesKcal","proteinG","fatG","carbohydrateG"])day[key]=Math.round(day[key]*100)/100}return{days:result,sourceHash:createHash("sha256").update(text).digest("hex")};
}

export function buildNutritionSql(parsed,userId=1){if(!Number.isSafeInteger(userId)||userId<1)throw new Error("Некорректный user id");const lines=["BEGIN TRANSACTION;"];for(const day of parsed.days){lines.push(`INSERT INTO nutrition_days(user_id,local_date,calories_kcal,protein_g,fat_g,carbohydrate_g,completeness,source,source_reference) VALUES(${userId},'${day.date}',${day.caloriesKcal},${day.proteinG},${day.fatG},${day.carbohydrateG},'aggregate_only','fatsecret_user_export','${parsed.sourceHash}') ON CONFLICT(user_id,local_date,source) DO UPDATE SET calories_kcal=excluded.calories_kcal,protein_g=excluded.protein_g,fat_g=excluded.fat_g,carbohydrate_g=excluded.carbohydrate_g,source_reference=excluded.source_reference,imported_at=CURRENT_TIMESTAMP;`)}lines.push("COMMIT;");return`${lines.join("\n")}\n`}
